// Generated by CoffeeScript 1.9.3
(function() {
  var Deferred, ScssFile, _, fs, path;

  fs = require('fs');

  _ = require('underscore');

  path = require('path');

  Deferred = require('when');

  ScssFile = (function() {
    ScssFile.prototype.importReg = new RegExp(/@import\s*"(.*?)"/g);

    function ScssFile(pathToFile, options) {
      var base, dir, promises;
      this.options = _.extend({
        encoding: 'utf-8',
        baseDir: null
      }, options);
      dir = path.dirname(pathToFile);
      this.deps = [];
      promises = [];
      if (!fs.existsSync(pathToFile)) {
        if (typeof (base = this.options).callback === "function") {
          base.callback();
        }
        return;
      }
      fs.readFile(pathToFile, this.options.encoding, (function(_this) {
        return function(err, content) {
          var base1, base2, imports;
          if (err || !content) {
            console.log(err);
            if (typeof (base1 = _this.options).callback === "function") {
              base1.callback();
            }
            return;
          }
          imports = content.match(_this.importReg);
          if (!Array.isArray(imports)) {
            if (typeof (base2 = _this.options).callback === "function") {
              base2.callback();
            }
            return;
          }
          imports.forEach(function(importStr) {
            var arRelative, dfd, fullPath, relativePath;
            dfd = Deferred.defer();
            relativePath = importStr.replace(/@import\s*/ig, '').replace(/"/g, '');
            arRelative = relativePath.split('/');
            arRelative[arRelative.length - 1] = "_" + arRelative[arRelative.length - 1];
            relativePath = arRelative.join('/');
            fullPath = path.resolve(dir, relativePath);
            if (fs.existsSync(fullPath + ".scss")) {
              fullPath = fullPath + ".scss";
            } else if (fs.existsSync(fullPath + ".sass")) {
              fullPath = fullPath + ".sass";
            } else if (_this.options.baseDir) {
              fullPath = path.resolve(_this.options.baseDir, relativePath);
              if (fs.existsSync(fullPath + ".scss")) {
                fullPath = fullPath + ".scss";
              } else if (fs.existsSync(fullPath + ".sass")) {
                fullPath = fullPath + ".sass";
              } else {
                return;
              }
            } else {
              return;
            }
            _this.deps.push(fullPath);
            new ScssFile(fullPath, _.extend({}, _this.options, {
              callback: function(list) {
                if (list == null) {
                  list = [];
                }
                _this.deps = _this.deps.concat(list);
                return dfd.resolve();
              }
            }));
            return promises.push(dfd.promise);
          });
          return Deferred.all(promises).then(function() {
            var base3;
            return typeof (base3 = _this.options).callback === "function" ? base3.callback(_this.deps) : void 0;
          });
        };
      })(this));
    }

    return ScssFile;

  })();

  module.exports = function(file, options, callback) {
    if (_.isFunction(options)) {
      callback = options;
      options = {};
    }
    return new ScssFile(file, _.extend(options, {
      callback: callback
    }));
  };

}).call(this);

//# sourceMappingURL=main.js.map
